from pathlib import Path
import sys

import streamlit as st

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.pipeline import build_player_features, head_to_head, load_data, optimize_team, player_pool, team_form

st.set_page_config(page_title="PlayXI", page_icon="🏏", layout="wide")


@st.cache_data(show_spinner="Loading IPL history…")
def app_data():
    deliveries, matches = load_data(ROOT / "data")
    return deliveries, matches, build_player_features(deliveries)


deliveries, matches, features = app_data()
teams = sorted(set(deliveries["batting_team"].dropna()) & set(deliveries["bowling_team"].dropna()))

st.title("🏏 PlayXI")
st.caption("A transparent, data-backed IPL fantasy XI assistant · Historical data through 3 June 2025")

left, right = st.columns(2)
team1 = left.selectbox("Team 1", teams, index=0)
team2 = right.selectbox("Team 2", teams, index=1 if len(teams) > 1 else 0)
if team1 == team2:
    st.warning("Choose two different teams.")
    st.stop()

pool = player_pool(features, (team1, team2))
default1 = pool[pool["team"].eq(team1)].head(11)["player"].tolist()
default2 = pool[pool["team"].eq(team2)].head(11)["player"].tolist()

st.subheader("Probable squads")
st.caption("Defaults are the highest-rated historical players for each franchise. Replace them with the confirmed playing XIs before generating a team.")
left, right = st.columns(2)
squad1 = left.multiselect(team1, pool[pool["team"].eq(team1)]["player"], default=default1, max_selections=11)
squad2 = right.multiselect(team2, pool[pool["team"].eq(team2)]["player"], default=default2, max_selections=11)

if st.button("Generate optimized XI", type="primary", use_container_width=True):
    selected_pool = pool[
        (pool["team"].eq(team1) & pool["player"].isin(squad1))
        | (pool["team"].eq(team2) & pool["player"].isin(squad2))
    ].reset_index(drop=True)
    try:
        xi = optimize_team(selected_pool)
    except ValueError as exc:
        st.error(str(exc))
    else:
        st.subheader("Recommended XI")
        shown = xi[["player", "team", "role", "predicted_points", "designation"]].copy()
        shown["predicted_points"] = shown["predicted_points"].round(1)
        st.dataframe(shown, hide_index=True, use_container_width=True)
        st.caption("Prediction = rolling average fantasy points before each player's latest recorded match. Captaincy is ranked by that estimate; no result is generated by an LLM.")

st.divider()
col1, col2, col3 = st.columns(3)
with col1:
    st.subheader("Last 5 meetings")
    st.dataframe(head_to_head(matches, team1, team2), hide_index=True, use_container_width=True)
with col2:
    st.subheader(f"{team1} form")
    st.dataframe(team_form(deliveries, team1), hide_index=True, use_container_width=True)
with col3:
    st.subheader(f"{team2} form")
    st.dataframe(team_form(deliveries, team2), hide_index=True, use_container_width=True)

with st.expander("Method and limitations"):
    st.markdown("""
- The source contains 278K+ IPL deliveries from 2008 through 3 June 2025.
- Player estimates use only prior-match fantasy points; they are not guarantees.
- Roles are inferred from historical batting and bowling participation and may need manual roster metadata.
- Injuries, venue, toss, current price, and post-dataset matches are not included.
""")
